GET http://localhost:3000?id=1

###
POST http://localhost:3000/insert
Content-Type: application/json

{
  "firstName": "Toretto",
  "lastName": "Dom",
  "email": "dom@toretto.com",
  "password": null
}

###
DELETE http://localhost:3000/delete?id=14

###
PUT http://localhost:3000/put?id=1
Content-Type: application/json

{
  "email" : "kyle@briyani.com"
}